//
//  MainPresenter.swift
//  CleanSwiftPractice
//
//  Created by Papon Supamongkonchai on 20/7/2565 BE.
//  Copyright (c) 2565 BE ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol MainPresentationLogic
{
  func presentSomething(response: Main.Login.Response)
}

class MainPresenter: MainPresentationLogic
{
  weak var viewController: MainDisplayLogic?
  
  // MARK: Do something
  
  func presentSomething(response: Main.Login.Response)
  {
      let viewModel = Main.Login.ViewModel(success: response.success)
    viewController?.displayDetail(viewModel: viewModel)
  }
}
